### PR TITLE
Add ability to output version numbers in cache download directory

### PR DESCRIPTION
**Pull request by EverlastingBugstopper**

### CODE REVIEW

**Comment by drager** [comment]
I think the code looks good! Looks like the tests are failing on Windows. However, I don't think it's your fault. Will have to investigate what's causing it to fail.

**Comment by EverlastingBugstopper** [comment]
Yeah it seems as if the Rust install is borked for some reason

```
"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\843ee89d-39b1-4759-9b02-86d05d918cbc.cmd""
info: profile set to 'default'
info: default host triple is i686-pc-windows-msvc
error: toolchain 'stable' is not installed
error: caused by: not a directory: 'C:\Users\VssAdministrator\.rustup\toolchains\stable-i686-pc-windows-msvc'
```

**Comment by drager** [comment]
@EverlastingBugstopper Yeah... I'm currently investigating it

**Comment by drager** [comment]
@EverlastingBugstopper I have pushed a fix for the CI into master. Rebase master into your branch and the tests should pass!

**Comment by drager** [comment]
@EverlastingBugstopper Want to try and merge master into your branch?

**Comment by EverlastingBugstopper** [comment]
whoopps - completely forgot about this

**Comment by aleclarson** [comment]
Can this be published now?

**Pull request merged**
